In [ ]:
#1 y 2
a_1=200
d=24
n=36
a_36=a_1+(n-1)*d
print(f'{a_36}')
sucesion = []
for i in range(36):
    n = i + 1
    sucesion.append(a_1+(n-1)*d)

suma = sum(sucesion)
print(f'{suma}')

1040
22320


In [ ]:
#4
a_1=2000000
r=1.012
n=9
a_9=a_1*(r**n)
print(f'{a_9}')

2226663.5926818973


In [ ]:
#5
a_2=1066
a_5=8528

r=(a_5/a_2)**(1/3)
print(f'{r}')

a_1=a_2/r

print(f'{a_1}')

a_9=a_1*r**(9-1)
print(f'{a_9}')

2.0
533.0
136448.0


In [ ]:
#6
final = 34112
termino = 0
dif = final - termino
n = 0
a_1 =533 
r = 2
while dif > 0:
  n += 1
  termino = a_1 * r**(n - 1)
  dif = final - termino
print(f'El término 34112 se ubica en la posición {n} de la sucesión.')

El término 34112 se ubica en la posición 7 de la sucesión.


In [ ]:
#7
a_4=1108000
a_12=1396000

d=(a_12-a_4)/8
print(f'{d}')
a_1=a_4-3*d
print(f'{a_1}')

36000.0
1000000.0


In [ ]:
#7
final=1828000
termino = 0
dif = final - termino
n = 0
a_1 =1000000
d = 36000
while dif > 0:
  n += 1
  termino = a_1 +(n-1)*d
  dif = final - termino
print(f'El término 1828000 se ubica en la posición {n} de la sucesión.')

El término 1828000 se ubica en la posición 24 de la sucesión.


In [ ]:
#8
import numpy as np

T=np.array([[300,272,240],
            [260,180,324]])

U=np.array([[1200,1250],
            [1100,1400],
            [1350,1200]])

C=np.dot(T,U)
print(f'{C}')

[[ 983200 1043800]
 [ 947400  965800]]


In [ ]:
#9 y 12
S=np.array([[360,280,150,420],
            [450,370,210,130],
            [240,260,320,340]])

C=np.array([[130,310,230,280],
            [370,340,520,370],
            [190,290,460,410]])

S1=0.8*S

C1=1.1*C

T=S1+C1
print(f'{T}')

[[431. 565. 373. 644.]
 [767. 670. 740. 511.]
 [401. 527. 762. 723.]]


In [ ]:
#13
A = np.fromfunction(lambda i, j: 2*(i+1)+3*(j+1), (3,3))
B = np.fromfunction(lambda i, j: 10*(i+1)*(j+1), (3,3))
print(f'{A}\n\n {B}')
C=np.dot(A,B)
print(f'\n{C}')

[[ 5.  8. 11.]
 [ 7. 10. 13.]
 [ 9. 12. 15.]]

 [[10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]

[[ 540. 1080. 1620.]
 [ 660. 1320. 1980.]
 [ 780. 1560. 2340.]]


In [ ]:
#14
A=np.array([[2,1],
            [3,-2]])
B=np.array([[10],
           [8]])

A_inv= np.linalg.inv(A)

C=np.dot(A_inv,B)
print(f'{C}')

[[4.]
 [2.]]


In [ ]:
#16
A=np.array([[2,3],[1,2]])

A_inv= np.linalg.inv(A)
print(f'{A_inv}')

[[ 2. -3.]
 [-1.  2.]]


In [ ]:
#17
A1=A.T
print(f'{A1}')

[[2 1]
 [3 2]]


In [ ]:
#19

B=A+A1
print(f'{B}')

[[4 4]
 [4 4]]


In [ ]:
#20
A=np.array([[2,3],
            [1,4]])
B=np.array([[52],
           [56]])

A_inv= np.linalg.inv(A)

C=np.dot(A_inv,B)
print(f'{C}')

[[ 8.]
 [12.]]
