3) ¿Cuántos milisegundos tarda el algoritmo en ejecutar una lista de 101 elementos?

In [2]:
def T(n):
    return 3*n + 5
print(f"{T(101)}")

308


5) El costo de procesamiento (en dólares) en función de las tareas a procesar en un sistema computacional, se puede modelar en la siguiente tabla: 
La forma algebraica de la función que relaciona ambas variables es:

In [5]:
import numpy as np
X = np.array([5, 10, 15, 20])
Y = np.array([200, 300, 400, 500])

pendiente, intercepto = np.polyfit(X, Y, 1)
print(f"La pendiente es {pendiente:.2f} y el coeficiente de posición es {intercepto:.2f}")

La pendiente es 20.00 y el coeficiente de posición es 100.00


6) La cantidad de usuarios de una aplicación móvil que ha sido lanzada recientemente, se puede modelar mediante la función U paréntesis izquierdo t paréntesis derecho igual 1.000 por e elevado a 0 coma 1 por t fin elevado, donde t es el tiempo transcurrido desde que se lanzó la aplicación, en meses.



¿Cuántos usuarios, aproximadamente tendrá la aplicación luego de transcurrir 1 año? Aproxime su resultado al entero.

In [7]:
import numpy as np

def U(t):
    return 1000*np.exp(0.1 * t)

print(f"{U(12):.0f}")

3320


7) El tamaño de una base de datos en terabytes (TB) crece exponencialmente en función del tiempo en años, a través del siguiente modelo:

D(t) = 2 X 1,2 elevado a t



¿Cuántos años deben pasar que la base de datos tenga un tamaño de 20 TB?

In [9]:
import numpy as np
from scipy.optimize import fsolve
def D(t):
    return 2 * 1.2**t - 20

xo = np.linspace(0, 20, 1)
solucion = fsolve(D, xo)

print(f"{solucion}")

[12.62925314]


8) Se tiene un sistema para generar números de serie para un determinado producto. El primer número de serie es 1.000 y cada número de serie se incrementará en 5 respecto al número de serie anterior. ¿Cuál será el número de serie del producto asociado a la posición 25?

In [11]:
a_1 = 1000
d = 5
n = 25
a_25 = a_1 + (n - 1) * d

print(f"{a_25}")

1120


9) Sea la sucesión a_n = 5n**3 - 2n. ¿Cuál es el término de la décima quinta posición?

In [13]:
def a(n):
    return 5 * n**3 - 2 * n

print(f"{a(15)}")

16845


10) Un algoritmo demora en procesar un solo registro en 2,1 minutos; dos registros en 2,2 y tres registros en 2,3 minutos. Si se sigue el mismo patrón de crecimiento, ¿cuántos registros procesa el algoritmo en 5,6 minutos?

5,6 = 2,1 + (n - 1) X 0,1
5,6 - 2,1 = (n - 1) X 0,1
3,5/0,1 = n - 1
35 + 1 = n
36 = n

In [14]:
final =  5.6
termino = 0
dif = final - termino
a_1 = 2.1
d = 0.1
while dif > 0:
    n += 1
    termino = a_1 + (n - 1) * d
    dif = final - termino
print(f"El término 5.6 se ubica en la posición {n} de la suceción")

El término 5.6 se ubica en la posición 36 de la suceción


13) En una tienda recién inaugurada, la primera semana ha vendido 300 unidades de un producto determinado y se espera que las ventas aumenten en 40 unidades cada semana. ¿Cuántas unidades del producto se proyecta vender en total al cabo de 2 meses? Considere que 1 mes equivale a 4 semanas.

In [16]:
a_1 = 300
d = 40
n = 8
sucesion = []
for i in range(8):
    n = i + 1
    sucesion.append(a_1 + (n - 1) * d)

suma = sum(sucesion)
print(f"{suma}")

3520


14) En una sucesión geométrica, el cuarto término es 24 y el sexto término es 96. Determine el valor del noveno término.

In [21]:
a_4 = 24
a_6 = 96

r = (a_6/a_4)**(1/2)
print(f"{r}")

a_1 = a_4/r**3
print(f"a_1 = {a_1}")

n = 9
a_9 = a_1 * r**(n - 1)
print(f"a_9 = {a_9}")

2.0
a_1 = 3.0
a_9 = 768.0


Responde la 16, 17 y 18 en base a un ejercicio

16) Si un día, el servidor B aumenta su consumo en un 20%, ¿cuántos gigabytes consumiría en dicho día por concepto de almacenamiento en la aplicación 3?

In [22]:
import numpy as np

B = np.array([[1, 7],
              [4, 6],
              [6, 5]])

B_1 = 1.2 * B
print(f"{B_1}")

[[1.2 8.4]
 [4.8 7.2]
 [7.2 6. ]]


17) Sea S igual A más B. El elemento s subíndice 21 se interpreta de la siguiente manera:



"El consumo diario total entre los dos tipos de recursos, para cada servidor es 12 GB".



Indique si la afirmación es Verdadera o Falsa.

In [24]:
import numpy as np

A = np.array([[4, 6],
              [8, 5],
              [2, 7]])

B = np.array([[1, 7],
              [4, 6],
              [6, 5]])

S = A + B

print(f"{S}")
print(f"FALSOOOOO")

[[ 5 13]
 [12 11]
 [ 8 12]]
FALSOOOOO


19) La matriz A igual abrir paréntesis a subíndice i j fin subíndice cerrar paréntesis nos indica la cantidad de acciones tipo j, pertenecientes a una empresa, que posee el inversionista i.

Por otra parte, la matriz E igual abrir paréntesis e subíndice i j fin subíndice cerrar paréntesis nos detalla el valor unitario de la acción tipo i de esta empresa, cotizado en euros, durante el día hábil j de la semana pasada.



Las matrices A y E tienen orden 15 x 10 y 10 x 5 respectivamente y se definen por las siguientes expresiones:



a subíndice i j fin subíndice igual 20 por i j



e subíndice i j fin subíndice igual 4 por i más j



¿En cuánto está evaluado, para el miércoles de la semana pasada, el total de acciones que posee en esta empresa el inversionista 8?

In [25]:
import numpy as np

A = np.fromfunction(lambda i, j: 20*(i + 1) * (j + 1), (15, 10))
E = np.fromfunction(lambda i, j: 4*(i + 1) + (j + 1), (10, 5))

C = np.dot(A, E)

print(f"{C}")

[[ 31900.  33000.  34100.  35200.  36300.]
 [ 63800.  66000.  68200.  70400.  72600.]
 [ 95700.  99000. 102300. 105600. 108900.]
 [127600. 132000. 136400. 140800. 145200.]
 [159500. 165000. 170500. 176000. 181500.]
 [191400. 198000. 204600. 211200. 217800.]
 [223300. 231000. 238700. 246400. 254100.]
 [255200. 264000. 272800. 281600. 290400.]
 [287100. 297000. 306900. 316800. 326700.]
 [319000. 330000. 341000. 352000. 363000.]
 [350900. 363000. 375100. 387200. 399300.]
 [382800. 396000. 409200. 422400. 435600.]
 [414700. 429000. 443300. 457600. 471900.]
 [446600. 462000. 477400. 492800. 508200.]
 [478500. 495000. 511500. 528000. 544500.]]


20) GB de RAM y 6 unidades de almacenamiento. Si la empresa ha adquirido un total de 72 GB de RAM y 40 unidades de almacenamiento, el sistema de ecuaciones que permite determinar la cantidad de estaciones de trabajo y servidores que se han instalado es:



abrir tabla fila celda 4 x más 8 y igual 72 fin celda fila celda 2 x más 6 y igual 40 fin celda fin tabla cerrar llaves



¿Cuántas estaciones de trabajo y servidores se han comprado?

In [26]:
A = np.array([[4, 8],
              [2, 6]])

B = np.array([[72],
              [40]])

A_inv = np.linalg.inv(A)

C = np.dot(A_inv, B)

print(f"{C}")

[[14.]
 [ 2.]]
